/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SERVER_GUI_CHAT;

import java.io.IOException;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author ismaele.carbonari
 */
public class SERVER extends javax.swing.JFrame {

    private DefaultListModel modello; //modello della lista
    private int porta;
    private Thread server;
    private ServerSocket serverSocket;

    /**
     * Creates new form SERVER
     */
    public SERVER() {

        initComponents();
        modello = new DefaultListModel();
        porta = 6789;
        InetAddress ia; //ip
        try {
            serverSocket = new ServerSocket(porta);
        } catch (IOException ex) {
            Logger.getLogger(SERVER.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ia = InetAddress.getLocalHost();
            TxTIP.setText(String.valueOf(ia));//inserisco nella label l'ip
            TxTPorta.setText(String.valueOf(porta)); //inserisco nella label porta
        } catch (UnknownHostException ex) {
            Logger.getLogger(SERVER.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPorta = new javax.swing.JLabel();
        lblLIP = new javax.swing.JLabel();
        TxTIP = new javax.swing.JTextField();
        TxTPorta = new javax.swing.JTextField();
        btnAvvia = new javax.swing.JButton();
        lstDisplay = new javax.swing.JScrollPane();
        lstServer = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");

        lblPorta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPorta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPorta.setText("Porta");

        lblLIP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLIP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLIP.setText("Indirizzo IP");

        TxTIP.setEditable(false);
        TxTIP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxTIP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxTIP.setText("***");

        TxTPorta.setEditable(false);
        TxTPorta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxTPorta.setText("****");

        btnAvvia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAvvia.setText("Avvia Server");
        btnAvvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvviaActionPerformed(evt);
            }
        });

        lstDisplay.setViewportView(lstServer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lstDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLIP, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxTIP)
                            .addComponent(TxTPorta, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                        .addGap(74, 74, 74)
                        .addComponent(btnAvvia)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLIP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxTIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxTPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAvvia)
                        .addGap(55, 55, 55)))
                .addComponent(lstDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvviaActionPerformed
        try {
            while (true) {
                Socket socket = serverSocket.accept();
                System.out.println("NUOVO COLLEGAMENTO: " + socket.getInetAddress().getHostName() + " - " + socket.getInetAddress());
                server = new Thread(new ServerTCP(socket));
                server.start();
            }

        } catch (IOException ex) {
            Logger.getLogger(SERVER.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnAvviaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SERVER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SERVER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SERVER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SERVER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SERVER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxTIP;
    private javax.swing.JTextField TxTPorta;
    private javax.swing.JButton btnAvvia;
    private javax.swing.JLabel lblLIP;
    private javax.swing.JLabel lblPorta;
    private javax.swing.JScrollPane lstDisplay;
    private javax.swing.JList<String> lstServer;
    // End of variables declaration//GEN-END:variables
}
